# 4. Pandas

1. **Introducción a Pandas**

In [1]:
import pandas as pd

In [2]:
?pd

Type:        module
String form: <module 'pandas' from 'c:\\Users\\Alejo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\alejo\appdata\local\programs\python\python311\lib\site-packages\pandas\__init__.py
Docstring:
pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.


2. **Estructuras de Datos en Pandas**


   - Series: Creación y operaciones básicas.

In [3]:
# una serie es un array unidimensional con un índice
# similar a un diccionario de python

serie1 = pd.Series(['a', 'b', 'c', 'd', 'e'], name='letras')
serie1

# los atributos principales de una serie son: nombre, índice, un valor y un tipo de dato (dtype)

0    a
1    b
2    c
3    d
4    e
Name: letras, dtype: object

- DataFrame: Creación y manipulación.

In [4]:
# Un dataframe es una estructura de datos multidimensional
# similar a una hoja de cálculo de excel
# se podría decir que es un conjunto de series

df1 = pd.DataFrame({'numeros': [1, 2, 3, 4, 5],
                    'listas' : [['matemática', 'lenguaje'], ['matemática, economía'], ['lenguaje', 'economía', 'matemática'], [], ['matemática']],
                    'letras' : ['a', 'b', 'c', 'd', 'e']},
                    index=['alumno 1', 'alumno 2', 'alumno 3', 'alumno 4', 'alumno 5'])



df1

          numeros                            listas letras
alumno 1        1            [matemática, lenguaje]      a
alumno 2        2            [matemática, economía]      b
alumno 3        3  [lenguaje, economía, matemática]      c
alumno 4        4                                []      d
alumno 5        5                      [matemática]      e

In [5]:
# los atributos principales de una serie son: index, columns, values y dtypes
df1.index

Index(['alumno 1', 'alumno 2', 'alumno 3', 'alumno 4', 'alumno 5'], dtype='object')

   - Indexación y selección de datos.

Existen dos formas de acceder a los datos de un dataframe (slicing):

- Por índice
- Por posición

In [6]:
# seleccionar listas de alumnos 1 y 2
df1.loc[['alumno 1', 'alumno 2'], 'listas']

# loc es para acceder por índice

alumno 1    [matemática, lenguaje]
alumno 2    [matemática, economía]
Name: listas, dtype: object

In [7]:
# seleccionar listas de alumnos 1 y 2
df1.iloc[[0, 1], 1]

# iloc es para acceder por posición

alumno 1    [matemática, lenguaje]
alumno 2    [matemática, economía]
Name: listas, dtype: object


3. **Carga y Almacenamiento de Datos**
   - Importar datos desde archivos CSV, Excel, y bases de datos.
   - Exportar datos a diferentes formatos.

In [8]:
df = pd.read_csv('https://gist.githubusercontent.com/noamross/e5d3e859aa0c794be10b/raw/b999fb4425b54c63cab088c0ce2c0d6ce961a563/cars.csv')
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [9]:
oecd = pd.read_html('https://en.wikipedia.org/wiki/List_of_countries_by_minimum_wage')[4]
oecd = oecd.set_index('Country')
oecd

# las columnas son unidemensionales?
# como eliminaría la última fila?

                                                                                     2018  \
                                                                                  Nominal
                                                                                   Annual
Country
(Australia,)                                                                      25970.8
(Belgium,)                                                                        21293.0
(Canada,)                                                                         20552.5
(Chile,)                                                                           4902.5
(Colombia,)                                                                        3451.3
(Czech Republic,)                                                                  6565.8
(Estonia,)                                                                         6869.8
(France,)                                                                         20353.1
(Germany,)                                                                        20414.6
(Greece,)                                                                          9208.7
(Hungary,)                                                                         5887.6
(Ireland,)                                                                        22446.1
(Israel,)                                                                         17992.6
(Japan,)                                                                          16805.5
(South Korea,)                                                                    16265.6
(Latvia,)                                                                          5877.2
(Lithuania,)                                                                       5498.9
(Luxembourg,)                                                                     27601.0
(Mexico,)                                                                          1236.0
(Netherlands,)                                                                    23618.0
(New Zealand,)                                                                    22541.6
(Poland,)                                                                          6709.8
(Portugal,)                                                                        9120.9
(Slovak Republic,)                                                                 6620.0
(Slovenia,)                                                                       11506.4
(Spain,)                                                                          11614.2
(Turkey,)                                                                          4943.8
(United Kingdom,)                                                                 20918.7
(United States,)                                                                  15353.3
(Costa Rica,)                                                                      5927.8
(Brazil,)                                                                          3023.8
(Russian Federation,)                                                              2053.7
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                           \

                                                                                   Hourly
Country
(Australia,)                                                                         13.1
(Belgium,)                                                                           10.2
(Canada,)                                                                             9.9
(Chile,)                                                                              2.1
(Colombia,)                                                                           1.2
(Czech Republic,)                                                                     3.3
(Estonia,)                                                                            3.4
(France,)                                                                            11.2
(Germany,)                                                                           10.0
(Greece,)                                                                             3.7
(Hungary,)                                                                            2.8
(Ireland,)                                                                           10.8
(Israel,)                                                                             8.1
(Japan,)                                                                              8.1
(South Korea,)                                                                        6.5
(Latvia,)                                                                             2.8
(Lithuania,)                                                                          2.8
(Luxembourg,)                                                                        13.3
(Mexico,)                                                                             0.6
(Netherlands,)                                                                       10.5
(New Zealand,)                                                                       10.8
(Poland,)                                                                             3.2
(Portugal,)                                                                           4.4
(Slovak Republic,)                                                                    2.1
(Slovenia,)                                                                           5.5
(Spain,)                                                                              5.6
(Turkey,)                                                                             2.4
(United Kingdom,)                                                                   12.23
(United States,)                                                                      7.4
(Costa Rica,)                                                                         2.2
(Brazil,)                                                                             1.3
(Russian Federation,)                                                                 1.0
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                           \
                                                                                      PPP
                                                                                   Annual
Country
(Australia,)                                                                      24481.2
(Belgium,)                                                                        22746.8
(Canada,)                                                                         20946.0
(Chile,)                                                                           7044.4
(Colombia,)                                                                        7677.4
(Czech Republic,)                                                                 10789.9
(Estonia,)                                                                         9890.2
(France,)                                                                         21860.3
(Germany,)                                                                        23439.6
(Greece,)                                                                         13040.0
(Hungary,)                                                                        11049.2
(Ireland,)                                                                        20585.9
(Israel,)                                                                         15416.5
(Japan,)                                                                          16607.6
(South Korea,)                                                                    19540.8
(Latvia,)                                                                          9168.8
(Lithuania,)                                                                       9694.0
(Luxembourg,)                                                                     25811.0
(Mexico,)                                                                          2238.5
(Netherlands,)                                                                    24859.9
(New Zealand,)                                                                    21716.3
(Poland,)                                                                         13704.8
(Portugal,)                                                                       12720.3
(Slovak Republic,)                                                                10001.1
(Slovenia,)                                                                       16015.8
(Spain,)                                                                          14731.8
(Turkey,)                                                                         12848.3
(United Kingdom,)                                                                 21132.2
(United States,)                                                                  15353.3
(Costa Rica,)                                                                      9326.5
(Brazil,)                                                                          4925.3
(Russian Federation,)                                                              4936.5
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                           \

                                                                                   Hourly
Country
(Australia,)                                                                         12.4
(Belgium,)                                                                           10.9
(Canada,)                                                                            10.1
(Chile,)                                                                              3.0
(Colombia,)                                                                           2.6
(Czech Republic,)                                                                     5.4
(Estonia,)                                                                            4.9
(France,)                                                                            12.0
(Germany,)                                                                           11.5
(Greece,)                                                                             5.2
(Hungary,)                                                                            5.2
(Ireland,)                                                                            9.9
(Israel,)                                                                             6.9
(Japan,)                                                                              8.0
(South Korea,)                                                                        7.8
(Latvia,)                                                                             4.4
(Lithuania,)                                                                          4.9
(Luxembourg,)                                                                        12.4
(Mexico,)                                                                             1.1
(Netherlands,)                                                                       11.0
(New Zealand,)                                                                       10.4
(Poland,)                                                                             6.6
(Portugal,)                                                                           6.1
(Slovak Republic,)                                                                    3.2
(Slovenia,)                                                                           7.7
(Spain,)                                                                              7.1
(Turkey,)                                                                             6.2
(United Kingdom,)                                                                    10.2
(United States,)                                                                      7.4
(Costa Rica,)                                                                         3.4
(Brazil,)                                                                             2.1
(Russian Federation,)                                                                 2.4
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                           \
                                                               Annual working hours(note)
                                                               Annual working hours(note)
Country
(Australia,)                                                                         1976
(Belgium,)                                                                           2086
(Canada,)                                                                            2080
(Chile,)                                                                             2346
(Colombia,)                                                                          2920
(Czech Republic,)                                                                    2000
(Estonia,)                                                                           2020
(France,)                                                                            1820
(Germany,)                                                                           2033
(Greece,)                                                                            2507
(Hungary,)                                                                           2112
(Ireland,)                                                                           2080
(Israel,)                                                                            2232
(Japan,)                                                                             2080
(South Korea,)                                                                       2508
(Latvia,)                                                                            2086
(Lithuania,)                                                                         1959
(Luxembourg,)                                                                        2077
(Mexico,)                                                                            2080
(Netherlands,)                                                                       2253
(New Zealand,)                                                                       2080
(Poland,)                                                                            2086
(Portugal,)                                                                          2086
(Slovak Republic,)                                                                   3145
(Slovenia,)                                                                          2086
(Spain,)                                                                             2086
(Turkey,)                                                                            2086
(United Kingdom,)                                                                    2079
(United States,)                                                                     2080
(Costa Rica,)                                                                        2711
(Brazil,)                                                                            2346
(Russian Federation,)                                                                2086
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                     2019  \
                                                                                  Nominal
                                                                                   Annual
Country
(Australia,)                                                                      26388.5
(Belgium,)                                                                        21410.8
(Canada,)                                                                         20880.7
(Chile,)                                                                           5101.7
(Colombia,)                                                                        3533.7
(Czech Republic,)                                                                  7064.3
(Estonia,)                                                                         7254.2
(France,)                                                                         20435.6
(Germany,)                                                                        20916.3
(Greece,)                                                                         10103.7
(Hungary,)                                                                         6151.5
(Ireland,)                                                                        22819.4
(Israel,)                                                                         17842.5
(Japan,)                                                                                -
(South Korea,)                                                                    17968.1
(Latvia,)                                                                          5776.5
(Lithuania,)                                                                       7455.7
(Luxembourg,)                                                                     28073.1
(Mexico,)                                                                          1386.1
(Netherlands,)                                                                    23586.2
(New Zealand,)                                                                    23330.0
(Poland,)                                                                          7032.4
(Portugal,)                                                                        9403.6
(Slovak Republic,)                                                                 6985.5
(Slovenia,)                                                                       11910.7
(Spain,)                                                                          14105.4
(Turkey,)                                                                          5410.1
(United Kingdom,)                                                                 21544.6
(United States,)                                                                  15080.0
(Costa Rica,)                                                                      5961.6
(Brazil,)                                                                          3049.4
(Russian Federation,)                                                              2090.9
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                           \

                                                                                   Hourly
Country
(Australia,)                                                                         13.4
(Belgium,)                                                                           10.3
(Canada,)                                                                            10.0
(Chile,)                                                                              2.2
(Colombia,)                                                                           1.2

Exportación

In [10]:
oecd.to_csv('oecd.csv')


4. **Exploración de Datos con Pandas**
   - Visualización de los primeros y últimos registros.
   - Resumen estadístico de los datos.
   - Manejo de valores faltantes.

In [11]:
mw = pd.read_html('https://en.wikipedia.org/wiki/List_of_countries_by_minimum_wage')[3]
mw = mw.set_index(('Country','Country'))
mw

                                                         Minimum wage  \
                                                         Minimum wage
(Country, Country)
Afghanistan         Afs. 5,500 (US$67) per month for non-permanent...
Albania             40,000 lek (US$430) per month. The law establi...
Algeria             DA 20,000 (US$156.19) per month, nationally.[1...
Andorra                                   €7.42 (USD8.33) hourly.[16]
Angola              Kz 32,181 (US$61) per month; paid thirteen tim...
...                                                               ...
Venezuela           The minimum wage in Venezuela is Bs. 400,000 p...
Vietnam             Varies by region; Region I: VND 4,420,000 per ...
Yemen               None; the minimum civil service wage was YRls ...
Zambia              Varies by sector; ZK 993.6 (US$81) per month f...
Zimbabwe            None, except for agricultural and domestic wor...

                             Annual               Workweek (hours)[4]  \
                   Nominal (US$)[6] PPP (Int$)[7] Workweek (hours)[4]
(Country, Country)
Afghanistan                  858.00        3272.0                  40
Albania                     4637.00        8697.0                  40
Algeria                     1777.00        6247.0                  40
Andorra                    18253.00       13493.0                  40
Angola                       663.00        3161.0                  44
...                             ...           ...                 ...
Venezuela                     10.32           NaN                 NaN
Vietnam                     1591.00        4089.0                  40
Yemen                           NaN           NaN                  48
Zambia                       596.00        3180.0                  48
Zimbabwe                        NaN           NaN                 NaN

                             Hourly                \
                   Nominal (US$)[8] PPP (Int$)[9]
(Country, Country)
Afghanistan                    0.41          1.57
Albania                        2.23          4.18
Algeria                        0.85          3.00
Andorra                        8.00          6.00
Angola                         0.29          1.38
...                             ...           ...
Venezuela                       NaN           NaN
Vietnam                        0.76          1.97
Yemen                           NaN           NaN
Zambia                         0.24          1.27
Zimbabwe                        NaN           NaN

                   Percent of GDP per capita[5]      Effective per
                   Percent of GDP per capita[5]      Effective per
(Country, Country)
Afghanistan                              168.3%               2017
Albania                                   75.4%       1 April 2023
Algeria                                   41.6%         1 May 2020
Andorra                                     28%     1 January 2023
Angola                                      49%               2022
...                                         ...                ...
Venezuela                                   NaN         1 May 2020
Vietnam                                     65%     1 January 2020
Yemen                                       NaN               2013
Zambia                                    80.8%  10 September 2018
Zimbabwe                                    NaN               2012

[201 rows x 8 columns]


5. **Manipulación de Datos con Pandas**
   - Filtrado de datos basado en condiciones.
   - Agregación y agrupación de datos.
   - Combinación de DataFrames.

In [12]:
mw.describe()

                Annual                          Hourly
      Nominal (US$)[6]  PPP (Int$)[7] Nominal (US$)[8] PPP (Int$)[9]
count       159.000000     156.000000       158.000000    156.000000
mean       6078.505157    9806.762821         2.885316      4.522436
std        7738.458336   14160.042836         3.776989      6.319179
min           0.000000       1.000000         0.000000      0.000000
25%         944.500000    2836.250000         0.432500      1.277500
50%        2792.000000    6592.000000         1.270000      2.810000
75%        7864.500000   12334.250000         3.970000      5.842500
max       33487.000000  126873.000000        16.100000     50.830000

In [13]:
sales  = pd.read_csv('https://raw.githubusercontent.com/alejo-acosta/curso-python-ciee/main/data/sales.csv')
items  = pd.read_csv('https://raw.githubusercontent.com/alejo-acosta/curso-python-ciee/main/data/items.csv')
stores = pd.read_csv('https://raw.githubusercontent.com/alejo-acosta/curso-python-ciee/main/data/stores.csv')
oil    = pd.read_csv('https://raw.githubusercontent.com/alejo-acosta/curso-python-ciee/main/data/oil.csv')

C:\Users\Alejo\AppData\Local\Temp\ipykernel_17996\2817981066.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  sales  = pd.read_csv('https://raw.githubusercontent.com/alejo-acosta/curso-python-ciee/main/data/sales.csv')

In [14]:
sales['date'].astype('datetime64[s]')

0         2013-01-01
1         2013-01-01
2         2013-01-01
3         2013-01-01
4         2013-01-01
             ...
1131724   2017-08-15
1131725   2017-08-15
1131726   2017-08-15
1131727   2017-08-15
1131728   2017-08-15
Name: date, Length: 1131729, dtype: datetime64[s]

In [15]:
sales.shape

(1131729, 7)

In [16]:
oil.dtypes

date           object
dcoilwtico    float64
dtype: object

In [17]:
oecd

                                                                                     2018  \
                                                                                  Nominal
                                                                                   Annual
Country
(Australia,)                                                                      25970.8
(Belgium,)                                                                        21293.0
(Canada,)                                                                         20552.5
(Chile,)                                                                           4902.5
(Colombia,)                                                                        3451.3
(Czech Republic,)                                                                  6565.8
(Estonia,)                                                                         6869.8
(France,)                                                                         20353.1
(Germany,)                                                                        20414.6
(Greece,)                                                                          9208.7
(Hungary,)                                                                         5887.6
(Ireland,)                                                                        22446.1
(Israel,)                                                                         17992.6
(Japan,)                                                                          16805.5
(South Korea,)                                                                    16265.6
(Latvia,)                                                                          5877.2
(Lithuania,)                                                                       5498.9
(Luxembourg,)                                                                     27601.0
(Mexico,)                                                                          1236.0
(Netherlands,)                                                                    23618.0
(New Zealand,)                                                                    22541.6
(Poland,)                                                                          6709.8
(Portugal,)                                                                        9120.9
(Slovak Republic,)                                                                 6620.0
(Slovenia,)                                                                       11506.4
(Spain,)                                                                          11614.2
(Turkey,)                                                                          4943.8
(United Kingdom,)                                                                 20918.7
(United States,)                                                                  15353.3
(Costa Rica,)                                                                      5927.8
(Brazil,)                                                                          3023.8
(Russian Federation,)                                                              2053.7
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                           \

                                                                                   Hourly
Country
(Australia,)                                                                         13.1
(Belgium,)                                                                           10.2
(Canada,)                                                                             9.9
(Chile,)                                                                              2.1
(Colombia,)                                                                           1.2
(Czech Republic,)                                                                     3.3
(Estonia,)                                                                            3.4
(France,)                                                                            11.2
(Germany,)                                                                           10.0
(Greece,)                                                                             3.7
(Hungary,)                                                                            2.8
(Ireland,)                                                                           10.8
(Israel,)                                                                             8.1
(Japan,)                                                                              8.1
(South Korea,)                                                                        6.5
(Latvia,)                                                                             2.8
(Lithuania,)                                                                          2.8
(Luxembourg,)                                                                        13.3
(Mexico,)                                                                             0.6
(Netherlands,)                                                                       10.5
(New Zealand,)                                                                       10.8
(Poland,)                                                                             3.2
(Portugal,)                                                                           4.4
(Slovak Republic,)                                                                    2.1
(Slovenia,)                                                                           5.5
(Spain,)                                                                              5.6
(Turkey,)                                                                             2.4
(United Kingdom,)                                                                   12.23
(United States,)                                                                      7.4
(Costa Rica,)                                                                         2.2
(Brazil,)                                                                             1.3
(Russian Federation,)                                                                 1.0
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                           \
                                                                                      PPP
                                                                                   Annual
Country
(Australia,)                                                                      24481.2
(Belgium,)                                                                        22746.8
(Canada,)                                                                         20946.0
(Chile,)                                                                           7044.4
(Colombia,)                                                                        7677.4
(Czech Republic,)                                                                 10789.9
(Estonia,)                                                                         9890.2
(France,)                                                                         21860.3
(Germany,)                                                                        23439.6
(Greece,)                                                                         13040.0
(Hungary,)                                                                        11049.2
(Ireland,)                                                                        20585.9
(Israel,)                                                                         15416.5
(Japan,)                                                                          16607.6
(South Korea,)                                                                    19540.8
(Latvia,)                                                                          9168.8
(Lithuania,)                                                                       9694.0
(Luxembourg,)                                                                     25811.0
(Mexico,)                                                                          2238.5
(Netherlands,)                                                                    24859.9
(New Zealand,)                                                                    21716.3
(Poland,)                                                                         13704.8
(Portugal,)                                                                       12720.3
(Slovak Republic,)                                                                10001.1
(Slovenia,)                                                                       16015.8
(Spain,)                                                                          14731.8
(Turkey,)                                                                         12848.3
(United Kingdom,)                                                                 21132.2
(United States,)                                                                  15353.3
(Costa Rica,)                                                                      9326.5
(Brazil,)                                                                          4925.3
(Russian Federation,)                                                              4936.5
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                           \

                                                                                   Hourly
Country
(Australia,)                                                                         12.4
(Belgium,)                                                                           10.9
(Canada,)                                                                            10.1
(Chile,)                                                                              3.0
(Colombia,)                                                                           2.6
(Czech Republic,)                                                                     5.4
(Estonia,)                                                                            4.9
(France,)                                                                            12.0
(Germany,)                                                                           11.5
(Greece,)                                                                             5.2
(Hungary,)                                                                            5.2
(Ireland,)                                                                            9.9
(Israel,)                                                                             6.9
(Japan,)                                                                              8.0
(South Korea,)                                                                        7.8
(Latvia,)                                                                             4.4
(Lithuania,)                                                                          4.9
(Luxembourg,)                                                                        12.4
(Mexico,)                                                                             1.1
(Netherlands,)                                                                       11.0
(New Zealand,)                                                                       10.4
(Poland,)                                                                             6.6
(Portugal,)                                                                           6.1
(Slovak Republic,)                                                                    3.2
(Slovenia,)                                                                           7.7
(Spain,)                                                                              7.1
(Turkey,)                                                                             6.2
(United Kingdom,)                                                                    10.2
(United States,)                                                                      7.4
(Costa Rica,)                                                                         3.4
(Brazil,)                                                                             2.1
(Russian Federation,)                                                                 2.4
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                           \
                                                               Annual working hours(note)
                                                               Annual working hours(note)
Country
(Australia,)                                                                         1976
(Belgium,)                                                                           2086
(Canada,)                                                                            2080
(Chile,)                                                                             2346
(Colombia,)                                                                          2920
(Czech Republic,)                                                                    2000
(Estonia,)                                                                           2020
(France,)                                                                            1820
(Germany,)                                                                           2033
(Greece,)                                                                            2507
(Hungary,)                                                                           2112
(Ireland,)                                                                           2080
(Israel,)                                                                            2232
(Japan,)                                                                             2080
(South Korea,)                                                                       2508
(Latvia,)                                                                            2086
(Lithuania,)                                                                         1959
(Luxembourg,)                                                                        2077
(Mexico,)                                                                            2080
(Netherlands,)                                                                       2253
(New Zealand,)                                                                       2080
(Poland,)                                                                            2086
(Portugal,)                                                                          2086
(Slovak Republic,)                                                                   3145
(Slovenia,)                                                                          2086
(Spain,)                                                                             2086
(Turkey,)                                                                            2086
(United Kingdom,)                                                                    2079
(United States,)                                                                     2080
(Costa Rica,)                                                                        2711
(Brazil,)                                                                            2346
(Russian Federation,)                                                                2086
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                     2019  \
                                                                                  Nominal
                                                                                   Annual
Country
(Australia,)                                                                      26388.5
(Belgium,)                                                                        21410.8
(Canada,)                                                                         20880.7
(Chile,)                                                                           5101.7
(Colombia,)                                                                        3533.7
(Czech Republic,)                                                                  7064.3
(Estonia,)                                                                         7254.2
(France,)                                                                         20435.6
(Germany,)                                                                        20916.3
(Greece,)                                                                         10103.7
(Hungary,)                                                                         6151.5
(Ireland,)                                                                        22819.4
(Israel,)                                                                         17842.5
(Japan,)                                                                                -
(South Korea,)                                                                    17968.1
(Latvia,)                                                                          5776.5
(Lithuania,)                                                                       7455.7
(Luxembourg,)                                                                     28073.1
(Mexico,)                                                                          1386.1
(Netherlands,)                                                                    23586.2
(New Zealand,)                                                                    23330.0
(Poland,)                                                                          7032.4
(Portugal,)                                                                        9403.6
(Slovak Republic,)                                                                 6985.5
(Slovenia,)                                                                       11910.7
(Spain,)                                                                          14105.4
(Turkey,)                                                                          5410.1
(United Kingdom,)                                                                 21544.6
(United States,)                                                                  15080.0
(Costa Rica,)                                                                      5961.6
(Brazil,)                                                                          3049.4
(Russian Federation,)                                                              2090.9
(Note: Annual wages divided by hourly wages,)  Note: Annual wages divided by hourly wages

                                                                                           \

                                                                                   Hourly
Country
(Australia,)                                                                         13.4
(Belgium,)                                                                           10.3
(Canada,)                                                                            10.0
(Chile,)                                                                              2.2
(Colombia,)                                                                           1.2

In [18]:
sales.head(10)

   Unnamed: 0   id        date  store_nbr  item_nbr  unit_sales onpromotion
0         137  137  2013-01-01         25    329362         1.0         NaN
1         167  167  2013-01-01         25    378685         8.0         NaN
2         171  171  2013-01-01         25    410257         1.0         NaN
3         201  201  2013-01-01         25    464263         2.0         NaN
4         225  225  2013-01-01         25    514242         4.0         NaN
5         365  365  2013-01-01         25    789905         5.0         NaN
6         528  528  2013-01-01         25   1047756         8.0         NaN
7         719  719  2013-01-02          1    227728         7.0         NaN
8         823  823  2013-01-02          1    329071         5.0         NaN
9         824  824  2013-01-02          1    329362         5.0         NaN

In [19]:
sales.dtypes

Unnamed: 0       int64
id               int64
date            object
store_nbr        int64
item_nbr         int64
unit_sales     float64
onpromotion     object
dtype: object


6. **Operaciones Avanzadas**
   - Aplicación de funciones a los datos.
   - Operaciones con fechas y tiempos.
   - Uso de expresiones lambda y apply.


8. **Visualización de Datos con Pandas**
   - Gráficos básicos con Pandas.
   - Uso de bibliotecas de visualización externas (ej. Matplotlib, Seaborn).